# Created by packaging/winget/render.sh in github.com/dagsommer/boks
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dagsommer.boks
PackageVersion: 0.1.22
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.22000.0
InstallerType: zip
NestedInstallerType: portable
Commands:
- boks
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: boks_0.1.22_windows_amd64/boks.exe
    PortableCommandAlias: boks
  InstallerUrl: https://github.com/dagsommer/boks/releases/download/v0.1.22/boks_0.1.22_windows_amd64.zip
  InstallerSha256: 3585E683B350C15DCAB5E3BC8A8C70B0F53724A64144EF221300426DD40C0153
ManifestType: installer
ManifestVersion: 1.12.0
