# Created by packaging/winget/render.sh in github.com/dagsommer/boks
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dagsommer.boks
PackageVersion: 0.1.23
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.22000.0
InstallerType: zip
NestedInstallerType: portable
Commands:
- boks
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: boks_0.1.23_windows_amd64/boks.exe
    PortableCommandAlias: boks
  InstallerUrl: https://github.com/dagsommer/boks/releases/download/v0.1.23/boks_0.1.23_windows_amd64.zip
  InstallerSha256: CED15FAA425179BA94D588FB0C68520FE49CC09F3E23126A95A7C3DE6A5FE075
ManifestType: installer
ManifestVersion: 1.12.0
